### ISSUE TITLE
Gitlab Support

### ISSUE THREAD

**Issue by axelrindle** [axelrindle/github-version-checker#15]
I plan to add Gitlab Support.

### Todo's

- [x] Move Github code to separated package
- [x] Add abstractions
- [x] Gitlab REST API
- [x] Gitlab GraphQL API

#### REST

```
GET https://gitlab.com/api/v4/projects/13083/repository/tags?order_by=version&sort=desc
```

#### GraphQL

```graphql
{
  project(fullPath: "gitlab-org/gitlab-foss") {
    releases(first: 1) {
      nodes {
        tagName
        upcomingRelease
        links {
          selfUrl
        }
      }
    }
  }
}
```
